inherit_gem:
  rubocop-github:
    - config/default_edge.yml
AllCops:
  Exclude:
    - 'bin/**/*'
    - '.git/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/Documentation:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '**/*.gemspec'