name: Specs

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rspec

      - name: Run linters
        run: |
          bundle exec rubocop --parallel
        continue-on-error: false
